### ISSUE TITLE
Оформление не по гайду:( 

### ISSUE THREAD

**Issue by denver411** [MiMisar/HomeWork3#2]
https://github.com/MiMisar/HomeWork3/blob/2cde3eb587ff1655b5902118de568dd5f4251ff5/index.html#L7

Привыкай сразу делать аккуратно, часто замечания по этому вопросу прилетают:)

**Comment by MiMisar** [comment]
Имеешь ввиду из-за того что а строчку одну написано?

**Comment by denver411** [comment]
Ага, именно так

**Comment by denver411** [comment]
https://github.com/netology-code/codestyle
Тебе в помощь

**Comment by MiMisar** [comment]
О! Спасибо большое.
