### ISSUE TITLE
Лучше не указывать тег в селекторе, без необходимости "усиления" селектора

### ISSUE THREAD

**Issue by denver411** [MiMisar/HomeWork3#3]
https://github.com/MiMisar/HomeWork3/blob/2cde3eb587ff1655b5902118de568dd5f4251ff5/style.css#L36

Часто для SEO теги меняют, и чтобы стили не слетели, лучше в селекторе только класс указывать.

**Comment by MiMisar** [comment]
Понял, спасибо.
